'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import {ThemeProvider} from '@material-tailwind/react'
import { UserContextProvider, useUserContext } from './auth/appContext'
import { useCookies } from 'react-cookie'
import { useMemo } from 'react'
import {CookiesProvider} from 'react-cookie'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      
      <body className={inter.className}>
        <CookiesProvider>
          <UserContextProvider>
            {children}
          </UserContextProvider>
        </CookiesProvider>
      </body>
    </html>
  )
}
